### PR TITLE
cargo-hf2: Update deprecated hidapi usage

### PR DESCRIPTION
**Pull request by gkelly**
Tested by flashing Seeeduino XIAO (with the other open PR I have patched on top), which worked.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
is there a cargo toml update to go with this or is upstream broken?

**Comment by gkelly** [comment]
> is there a cargo toml update to go with this or is upstream broken?

The build's not broken it just gives deprecation warnings for those items. I think `cargo-hf2` is getting hidapi `1.2.1` transitively from `hf2`. I guess that means the local `Cargo.toml` can be rolled to `1.2.1` as well, let me do that.

**Comment by gkelly** [comment]
Updated the `hf2-cli` usage as well and the version there.

**Comment by jacobrosenthal** [comment]
Oh I see. But yeah lets get the version bump while were at it. Thanks!

**Pull request merged**
