### PR TITLE
Fix an incorrect number of zero bytes being inserted between sections

### PR DESCRIPTION
**Pull request by yvt**
This PR fixes a bug in the `elf_to_bin` function.

When processing the `i`-th section (where `i > 0`), `start[i] - (start[0] + len[i - 1])` zero bytes are inserted *after* that section. This doesn't make any sense and causes sections to be written at incorrect locations under certain circumstances.

This PR updates the code so that `start[i] - (start[i - 1] + len[i - 1])` = `start[i] - end[i - 1]` zero bytes are inserted *before* each section.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Man that loop has all the bugs. Do you have a binary showing the problem we can add to those test cases?

**Comment by jacobrosenthal** [comment]
And does this by any chance close https://github.com/jacobrosenthal/hf2-rs/issues/38
can we get  @sinyo-matu  to confirm if so?

**Comment by yvt** [comment]
> Do you have a binary showing the problem we can add to those test cases?

The problem is exhibited by [an example from my RTOS](https://github.com/yvt/r3/tree/%E2%9C%85-wio-terminal/examples/basic_wio_terminal), but I think I can whip up a smaller test case.

> And does this by any chance close #38 can we get @sinyo-matu to confirm if so?

No, it's unrelated.

**Comment by jacobrosenthal** [comment]
I threw a commit on unifying the if statements that I think is an improvement.
 
 Is this done? It tested a pygamer and it still works with this patch so seems ok

**Comment by yvt** [comment]
Yep, it's ready to merge.

**Comment by Rahix** [comment]
Just as a datapoint: The linker script changes in `cortex-m-rt` 0.7 seem to reliably trigger this bug.  Glad it's fixed!

**Pull request merged**
